### ISSUE TITLE
Implement do-while 

### ISSUE THREAD

**Issue by ustun** [leebyron/react-loops#10]
Lack of do-while severely hurts React adoption. It has been proven that almost always you enter a loop at least once, there is no sane reason to check if you will enter a loop at all on first invocation.  Do-while is much more performant than a for loop that  this will also allow us that the clock cycles we lose with immutablejs can be obtained from the additional CPU power this feature would bring, making immutablejs more popular.

**Comment by leebyron** [comment]
I will file this under: features to consider in the future when motivated by a compelling use case.

Thanks for writing it out!
