### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by tomByrer** [leebyron/react-loops#14]
I was about to use this lib for `<IF>` but seems that was [nuked](https://github.com/leebyron/react-loops/pull/12).  Not a big deal, but there is no warning in the README for the changes, nor there are any releases.

BTW, an drastic API change such as a deletion is usually a [2.0.0 change](https://semver.org/#spec-item-8).  If the API is still unstable then that would be typically 0.y.z release (though some are popular for years without hitting v1.0.0).

**Comment by leebyron** [comment]
Yes! I'm so sorry for churning you around so soon after publishing this. I considered first publishing as an -rc release or 0.x because of early API churn and probably should have in hindsight.

A changelog is a good idea, and I will add that!
