### ISSUE TITLE
react-loops === react-listable ?

### ISSUE THREAD

**Issue by victufell** [leebyron/react-loops#17]
What's the difference between [lib](https://github.com/victorvoid/react-listable) and yours? It seems like a fork.

**Comment by kelsonpw** [comment]
This library seems to cover a lot more edge cases / is thoroughly tested and uses typescript

**Comment by leebyron** [comment]
Thanks for highlighting! I haven't seen that library before. Looks like it seeks to solve the same problem with a similar API. I'll include it in the list in the readme
