### ISSUE TITLE
TypeScript type definitions aren't correct

### ISSUE THREAD

**Issue by ChaosinaCan** [leebyron/react-loops#19]
The following TypeScript code...

```typescript
import * as React from 'react';
import { For } from 'react-loops';

const Test: React.FunctionComponent = (props) => {
    const things = {
        foo: 1,
        bar: 2,
    };
    return (
        <dl>
            <For in={things} as={(item, {key}) =>
                <>
                    <dt>{key}</dt>
                    <dd>{item}</dd>
                </>
            }/>
        </dl>
    );
};
```

...results in this error:

> JSX element type 'ReactNode' is not a constructor function for JSX elements.
  Type 'undefined' is not assignable to type 'Element | null'.ts(2605)

I found a similar issue at https://github.com/ganderzz/react-scroll-to/issues/89, and the resolution there was to change the return type from `React.ReactNode` to `JSX.Element`. Doing the same to the return value of `For()` in react-loops.d.ts appears to fix the problem.

**Comment by leebyron** [comment]
Thanks! 

In the future if you're aware of the fix, feel free to send a PR
